# Generated by Django 4.0.5 on 2022-10-18 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
