# Generated by Django 4.0.5 on 2022-12-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_userpost_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
    ]
